$('#images').viewer({
    backdrop:true,
    button:true,
    navbar:true,
    title:true,
    toolbar:true,
    className:'',
    container:'body',
    filter:null,
    fullscreen:true,
    initialViewIndex: 0,
    inline:false,
    interval: 5000,
    keyboard:true,
    loading:true,
    loop:true,
    minWidth: 200,
    minHeight: 100,
    movable:true,
    rotatable:true,
    scalable:true,
    zoomable:true,
    zoomOnTouch:true,
    zoomOnWheel:true,
    slideOnTouch:true,
    toggleOnDblclick:true,
    tooltip:true,
    transition:true,
    zIndex: 2015,
    zIndexInline: 0,
    zoomRatio: 0.1,
})